/*
Prerequisites:
	- Clone the following repo: https://github.com/roed314/FiniteGroups.git
	- Acquire the following files: group_descriptions.txt and divisions.txt
	- Install qsopt-ex.
Usage:
	load "main.m";
This will compute IMBs of all groups of order <= 100.
	time cache := ComputeAll(100);
	GetGroupData(cache, SymmetricGroup(4));
This will write a file dmbs.out with the DMBs of all nontrivial transitive permutation groups of degree <= 10.
	time WriteDMBs(cache, 10);
This will write a file imbs.out with the IMBs of all computed groups.
	time WriteIMBs(cache);
*/

SetColumns(0);

AttachSpec("FiniteGroups/Code/spec");
load "qsopt-ex.m";
load "IMB_LP_Solver.m";
load "convex-dominated.m";

Qrat := Rationals();

// A group together with an ordering of the conjugacy classes and inertia types.
GroupCoordinates := recformat<
	// The finite group.
	group : Grp,
	// A list of representatives of the conjugacy classes of elements.
	classes : SeqEnum,
	// A list of elements generating representatives of the inertia types.
	// (An inertia type is a conjugacy class of nontrivial cyclic subgroups.)
	inertia_types : SeqEnum,
	// conj_cl_to_inertia_type[i] = the index of the inertia type containing the cyclic group generated by classes[i]. (By convention, this is 0 if classes[i] = identity.)
	conj_cl_to_inertia_type : SeqEnum
>;

GroupData := recformat<
	// The GroupCoordinates.
	coords,
	// The inertial multiplicity bounds.
	imbs : SeqEnum
>;

// Inertial multiplicity bound.
IMB := recformat<
	bound : SeqEnum,
	proof
>;

// Discriminant multiplicity bound.
DMB := recformat<
	bound : Qrat,
	proof
>;

// Class group bound.
// TODO Document what exactly this means. Also, sum_savings is a horrible name.
CGB := recformat<
	sum_savings : Qrat,
	bound : Qrat,
	proof
>;

NormSubDat := recformat<
	subgroup,
	bounds
>;

// Returns the index of the inertial type <g>. Returns 0 if g is the identity.
function InertiaTypeGeneratedBy(coords, g)
	// We find the conjugacy class containing g by trying one conjugacy class at a time.
	// TODO There may be faster ways to do this.
	for i in [1..#coords`classes] do
		if IsConjugate(coords`group, coords`classes[i], g) then
			return coords`conj_cl_to_inertia_type[i];
		end if;
	end for;
	error "Did not find the conjugacy class containing g.";
end function;

// Computes GroupCoordinates for this group.
function ComputeGroupCoordinates(G)
	inertia_types := [];
	classes := Classes(G);
	power_map := PowerMap(G);
	n := #classes;
	conj_cl_to_inertia_type := [0 : i in [1..n]];
	for i in [1..n] do
		if conj_cl_to_inertia_type[i] eq 0 then
			// Generator of the conjugacy class.
			g := classes[i][3];
			// Order of g.
			ord := classes[i][1];
			if ord ne 1 then
				Append(~inertia_types, g);
				// Loop over all generators of the cyclic group generated by g.
				for j in [1..ord] do
					if Gcd(j, ord) eq 1 then
						conj_cl_to_inertia_type[power_map(i, j)] := #inertia_types;
					end if;
				end for;
			end if;
		end if;
	end for;
	return rec<GroupCoordinates |
		group := G,
		classes := [cl[3] : cl in classes],
		inertia_types := inertia_types,
		conj_cl_to_inertia_type := conj_cl_to_inertia_type
	>;
end function;

forward GetGroupData;

// Let G be a permutation group of degree >= 2.
// Returns a list of discriminant multiplicity bounds for G.
function ComputeDMBs(G)
	res := [];
	n := Degree(G);
	assert n ge 2;
	
	// Parameterizations in degrees <= 5 (Theorem 3.9).
	if n le 5 then
		Append(~res, rec<DMB |
			bound := 1,
			proof := "low-degree"
		>);
	end if;
	// TODO Other known special cases?
	// Schmidt bound (Theorem 3.13).
	Append(~res, rec<DMB |
		bound := (n+2)/4,
		proof := "schmidt"
	>);
	// Bhargava-Shankar-Wang (Theorem 3.14).
	if n ge 6 then
		g := Floor((n-1)/2);
		delta := 1/(2*n-2) - 1/(2^(2*g) * (2*n-2));
		Append(~res, rec<DMB |
			bound := (n+2)/4 - delta,
			proof := "bhargava-shankar-wang"
		>);
	end if;
	// Bhargava-Schmidt bound (Theorem 3.15).
	if IsPrimitive(G) then
		indG := Min([n - #CycleDecomposition(g[3]) : g in Classes(G) | not IsIdentity(g[3])]);
		Append(~res, rec<DMB |
			bound := (n-2)/4 + 1/indG,
			proof := "bhargava-schmidt"
		>);
	end if;
	// TODO Schmidt bound for towers (Theorem 3.16, Problem 3.17).
	// TODO Bounds from other invariants (Theorem 3.19, ...).
	
	// Return only the smallest bound.
	if #res ge 1 then
		best := res[1];
		for dmb in res do
			if best`bound gt dmb`bound then
				best := dmb;
			end if;
		end for;
		return [best];
	else
		return [];
	end if;
end function;

// Returns the comparison function x, y |-> f(x) < f(y).
function ByKey(f)
	return func<x, y | f(x) lt f(y) select -1 else (f(x) eq f(y) select 0 else 1)>;
end function;

// Returns a pruned list of imbs.
// 1) If any imb vector appears several times in the input, only the first one is kept. We thus only preserve the first proof trace for this vector.
// 2) Afterwards, any imb v is removed if there is another imb w with w <= v coordinate-wise.
// The running time is O(n^2 m) if there are n imbs in the input, which lie in m-dimensional space.
function PrunePartialOrder(imbs)
	if #imbs eq 0 then
		return [];
	end if;
	m := #imbs[1]`bound;
	// Order the imbs lexicographically.
	Sort(~imbs, ByKey(func<x | x`bound>));
	res := [];
	for v in imbs do
		// Only add v to res if there is no w that has already been added and that satisfies w <= v coordinate-wise.
		if not &or[&and[w`bound[i] le v`bound[i] : i in [1..m]] : w in res] then
			Append(~res, v);
		end if;
	end for;
	return res;
end function;

// Only keeps one imb per vertex of the convex hull of the input imbs + the positive octant.
function PruneConvexHull(imbs)
	point_to_imb := AssociativeArray();
	for imb in imbs do
		point_to_imb[imb`bound] := imb;
	end for;
	
	remaining_points := ConvexHullShadowGenerators([imb`bound : imb in imbs]);
	return [point_to_imb[v] : v in remaining_points];
	
// 	// This is an earlier, much slower attempt using standard magma commands.
// 	polytope := Polytope([imb`bound : imb in imbs]);
// 	m := #imbs[1]`bound;
// 	cone := PositiveQuadrant(m);
// 	polyhedron := polytope + cone;
// 	return [point_to_imb[Eltseq(v)] : v in Vertices(polyhedron)];
end function;

function ComputeGroupData(cache, G)
	coords := ComputeGroupCoordinates(G);
	inertia_types := coords`inertia_types;
	
	// TODO In those proofs that derive an imb for G from an imb for a different group Q, we record the imb of Q used, but this information by itself is not quite sufficient to easily recover the imb of G due to automorphisms of Q.
	
	imbs := [];
	if #G eq 1 then
		Append(~imbs, rec<IMB |
			bound := [Qrat | ],
			proof := <"trivial">
		>);
	elif IsNilpotent(G) then
		// This is technically redundant as it follows from "hypercenter".
		Append(~imbs, rec<IMB |
			bound := [1 : i in [1..#inertia_types]],
			proof := <"nilpotent">
		>);
	elif IsIsomorphic(G, SymmetricGroup(3)) then
		Append(~imbs, rec<IMB |
			bound := [1,1],
			proof := <"S3">
		>);
	elif #Center(G) ne 1 then
		H := Hypercenter(G);
		Q, pi := quo<G | H>;
		// For each IMB of the quotient group Q = G/H, we obtain an IMB of G.
		Qdata := GetGroupData(cache, Q);
		for Qimb in Qdata`imbs do
			bound := [Qrat | ];
			for g in inertia_types do
				if g in H then
					Append(~bound, 1);
				else
					Append(~bound, Qimb`bound[InertiaTypeGeneratedBy(Qdata`coords, pi(g))]);
				end if;
			end for;
			Append(~imbs, rec<IMB |
				bound := bound,
				proof := <"hypercenter", Qimb>
			>);
		end for;
	else
		// Try to apply Theorem 7.18. We only try abelian normal subgroups A of index <= max_index.
		// TODO More efficient way to find abelian normal subgroups?
		max_index := 20;
		for A in LowIndexSubgroups(G, max_index) do
			if not (#A ne 1 and IsAbelian(A) and IsNormal(G, A)) then
				continue;
			end if;
			for Wd in Subgroups(A) do
				W := Wd`subgroup;
				if #Core(G, W) ne 1 then
					continue;
				end if;
				NGW_mod_W, pi1 := quo<Normalizer(G, W) | W>;
				imA := pi1(A);
				H := Centralizer(NGW_mod_W, imA) @@ pi1;
				AmodW := quo<A | W>;
				AmodW_invariants := AbelianInvariants(AmodW);
				r := #AmodW_invariants;
				Q, pi := quo<G | A>;
				Qdata := GetGroupData(cache, Q);
				phi, Gp, ker := CosetAction(Q, pi(H));
				// m = [G/A : H/A].
				m := Degree(Gp);
				class_group_bounds := [];
				// Corollary 7.24.
				Append(~class_group_bounds, rec<CGB |
					sum_savings := 0,
					bound := r/2,
					proof := "trivial"
				>);
				// Corollary 7.25.
				if Exponent(AmodW) eq 2 then
					delta := 2875/10000;
					if m le 4 then
						// Six author JAMS.
						Append(~class_group_bounds, rec<CGB |
							sum_savings := 0,
							bound := r * delta,
							proof := "six-author-JAMS"
						>);
					else
						// Bonolis.
						Append(~class_group_bounds, rec<CGB |
							sum_savings := 0,
							bound := r * (1/2 - 15/(28*m) + 3/(28*m*(m-1))),
							proof := "Bonolis"
						>);
					end if;
				end if;
				// Corollary 7.26.
				AmodW_ispgrp, AmodWp := IsPrimePower(#AmodW);
				Rest_ispgrp, Restp := IsPrimePower(Index(Q, Core(Q, pi(H))));
				if AmodW_ispgrp and Rest_ispgrp and AmodWp eq Restp then
					Append(~class_group_bounds, rec<CGB |
						sum_savings := 0,
						bound := 0,
						proof := "genus-theory"
					>);
				end if;
				if IsMaximal(Q, pi(H)) and #Core(Q, pi(H)) eq 1 then
					// Corollary 7.27, w_C.
					Append(~class_group_bounds, rec<CGB |
						sum_savings := 0,
						bound := &+[1/2 - 1/(2*AmodW_invariants[i]*(m-1)) : i in [1..r]],
						proof := "7.27"
					>);
					// Corollary 7.27, w_C'.
					// In the notes, l_1 refers to the largest invariant, whereas AmodW_invariants[1] is the smallest invariant and AmodW_invariants[r] is the largest.
					Append(~class_group_bounds, rec<CGB |
						sum_savings := Min(1, r/(AmodW_invariants[r]*(m-1)+1)),
						bound := r/2,
						proof := "7.27'"
					>);
				end if;
				// Average 2-torsion in cubic number fields.
				// TODO Check! Not currently in Robert's draft.
				// TODO Does this also work if G/A = C_3?
				if m eq 3 and #AmodW eq 2 and #Core(Q, pi(H)) eq 1 then
					Append(~class_group_bounds, rec<CGB |
						sum_savings := 1,
						bound := 1,
						proof := "avg-2-torsion"
					>);
				end if;
				// Due to the sum_savings parameter, there is not always a clear winner among the class group bounds. We just try all of them.
				// TODO Make this more efficient by eliminating the useless ones?
				for Qimb in Qdata`imbs do
					for cgb in class_group_bounds do
						bound := [Qrat | ];
						for g in inertia_types do
							if g in A then
								Append(~bound, 1);
							else
								Append(~bound,
									(1 - cgb`sum_savings) * Qimb`bound[InertiaTypeGeneratedBy(Qdata`coords, pi(g))]
									+ cgb`bound * (m - #CycleDecomposition(phi(pi(g))))
								);
							end if;
						end for;
						Append(~imbs, rec<IMB |
							bound := bound,
							proof := <"7.18", A, W, cgb, Qimb>
						>);
					end for;
				end for;
			end for;
		end for;
		
		// Iterate over conjugacy classes of subgroups of index <= max_perm_deg, which correspond to transitive permutation representations of degree <= max_perm_deg.
		max_perm_deg := 31;
		for H in LowIndexSubgroups(G, max_perm_deg) do
			deg := Index(G, H);
			phi, Gp, ker := CosetAction(G, H);
			assert Degree(Gp) eq deg;
			// Check that the action of G on G/H is faithful, i.e., the map phi : G -> Gp is an isomorphism.
			if #ker ne 1 then
				continue;
			end if;
			// IMBs from discriminant counting bounds.
			for dmb in ComputeDMBs(Gp) do
				// Indices of the inertia types for the permutation representation.
				indices := [deg - #CycleDecomposition(phi(g)) : g in inertia_types];
				Append(~imbs, rec<IMB |
					bound := [dmb`bound * ind : ind in indices],
					proof := <"disc", H, dmb>
				>);
			end for;
		end for;
		
		// Precompute data about G/N for all nontrivial normal subgroups N of G.
		nsg := NormalSubgroups(G);
		normal_subgroup_pair_limit := 1000;
		// We only try this if there are at most normal_subgroup_pair_limit normal subgroups.
		// TODO Do something smarter.
		if #nsg le normal_subgroup_pair_limit then
			normal_subgroups := [];
			for Nrec in nsg do
				N := Nrec`subgroup;
				if #N ne 1 then
					Q, pi := quo<G | N>;
					Qdata := GetGroupData(cache, Q);
					Nbounds := [];
					for Qimb in Qdata`imbs do
						bound := [Qrat | ];
						for g in inertia_types do
							if g in N then
								Append(~bound, 0);
							else
								Append(~bound, Qimb`bound[InertiaTypeGeneratedBy(Qdata`coords, pi(g))]);
							end if;
						end for;
						Append(~Nbounds, bound);
					end for;
					Append(~normal_subgroups, rec<NormSubDat | subgroup := N, bounds := Nbounds>);
				end if;
			end for;
			// Iterate over pairs of nontrivial normal subgroups intersecting trivially.
			// TODO Only iterate over pairs modulo outer automorphisms.
			for iN1 in [1..#normal_subgroups] do
				for iN2 in [iN1+1..#normal_subgroups] do
					N1 := normal_subgroups[iN1]`subgroup;
					N2 := normal_subgroups[iN2]`subgroup;
					if #(N1 meet N2) ne 1 then
						continue;
					end if;
					N1bounds := normal_subgroups[iN1]`bounds;
					N2bounds := normal_subgroups[iN2]`bounds;
					for N1bound in N1bounds do
						for N2bound in N2bounds do
							Append(~imbs, rec<IMB |
								bound := [N1bound[i] + N2bound[i] : i in [1..#inertia_types]],
								proof := <"generated-by", N1, N2, N1bound, N2bound>
							>);
						end for;
					end for;
				end for;
			end for;
		end if;
	end if;
	
	// Prune the list of imbs.
	imbs := PruneConvexHull(PrunePartialOrder(imbs));
	
	// Sanity check that all imbs are coordinatewise larger than or equal to the conjecturally best imb (1,...,1).
	for imb in imbs do
		if not &and[imb`bound[i] ge 1 : i in [1..#inertia_types]] then
			error "The computed imb", imb, "for the group", G, "is better than the conjectured best imb (1,...,1). This is either a bug or a counterexample to the conjecture.";
		end if;
	end for;
	
	return rec<GroupData |
		coords := coords,
		imbs := imbs
	>;
end function;

// A hash of G consisting of the order of G together with David Roe's hash function.
function full_hash(G)
	return [#G, hash(G)];
end function;

// If there is a group isomorphic to G in the cache, returns (true, data for G).
// Returns (false, 0) otherwise.
function MaybeGetGroupData(cache, G)
	ha := full_hash(G);
	if IsDefined(cache, ha) then
		for data in cache[ha] do
			// TODO We actually do not quite need to know an isomorphism between G and data`coords`group. It would suffice to know the resulting bijection between inertia types. Constructing just this bijection could be easier in some cases.
			isomorphic, phi := IsIsomorphic(data`coords`group, G);
			if isomorphic then
				// Apply the isomorphism phi to the cached data to obtain data for the group G.
				return true, rec<GroupData |
					coords := rec<GroupCoordinates |
						group := G,
						classes := [phi(g) : g in data`coords`classes],
						inertia_types := [phi(g) : g in data`coords`inertia_types],
						conj_cl_to_inertia_type := data`coords`conj_cl_to_inertia_type
					>,
					// TODO Should we apply the isomorphism to the proof trace or ignore it?
					imbs := data`imbs
				>;
			end if;
		end for;
	end if;
	return false, 0;
end function;

// If there is a group isomorphic to G in the cache, returns (data for G).
// Fails otherwise.
function GetGroupData(cache, G)
	ex, dat := MaybeGetGroupData(cache, G);
	if ex then
		return dat;
	else
		error "Group not found";
	end if;
end function;

// Compute data for all groups G of order <= max_order.
function ComputeAll(max_order)
	cache := AssociativeArray();
	for order in [1..max_order] do
		nr := NumberOfSmallGroups(order);
		for n in [1..nr] do
			G := SmallGroup(order, n);
			ha := full_hash(G);
			if not IsDefined(cache, ha) then
				cache[ha] := [];
			end if;
			Append(~cache[ha], ComputeGroupData(cache, G));
		end for;
	end for;
	return cache;
end function;

// Writes to the file one line of the form nTi|alpha for each transitive permutation group of degree <= max_degree that appears in the cache. Here, nTi is the label of the permutation group and alpha is our discriminant upper bound.
procedure WriteDMBs(cache, max_degree)
	Write("dmbs.out", "label|discriminant_multiplicity_bound" : Overwrite := true);
	Write("dmbs.out", "text|text");
	Write("dmbs.out", "");
	for deg in [2..max_degree] do
		nr := NumberOfTransitiveGroups(deg);
		for i in [1..nr] do
			G := TransitiveGroup(deg, i);
			ex, dat := MaybeGetGroupData(cache, G);
			if ex then
				indices := [deg - #CycleDecomposition(g) : g in dat`coords`inertia_types];
				bounds := [imb`bound : imb in dat`imbs];
				alpha := InertialUB_from_IMBs(indices, bounds);
				Write("dmbs.out", Sprintf("%oT%o|\"%o\"", deg, i, alpha));
			end if;
		end for;
	end for;
end procedure;

// Turns a sequence of strings into a string.
// Example: [] => "[]"
// Example: ["hello", "world"] => "[hello,world]"
function ArrayString(strs)
	res := "[";
	first := true;
	for s in strs do
		if first then
			first := false;
		else
			res *:= ",";
		end if;
		res *:= s;
	end for;
	res *:= "]";
	return res;
end function;

// Writes to the file one line of the form label|imbs for each group from group_descriptions.txt that appears in the cache. The inertia types are ordered as in divisions.txt.
procedure WriteIMBs(cache)
	ccs := AssociativeArray();
	divisions_file := Open("divisions.txt", "r");
	while not AtEof(divisions_file) do
		line := Gets(divisions_file);
		if IsEof(line) then
			break;
		end if;
		parts := Split(line, "|");
		labels := parts[1];
		elt := parts[2];
		pos := Maximum([i : i in [1..#labels] | labels[i] eq "."]);
		group_label := labels[1..pos-1];
		cc_label := labels[pos+1..#labels];
		if not IsDefined(ccs, group_label) then
			ccs[group_label] := [];
		end if;
		Append(~ccs[group_label], [cc_label, elt]);
	end while;
	delete divisions_file;
	group_descriptions_file := Open("group_descriptions.txt", "r");
	Write("imbs.out", "label|inertial_multiplicity_bounds" : Overwrite := true);
	Write("imbs.out", "text|text[][]");
	Write("imbs.out", "");
	nr_groups_not_computed := 0;
	while not AtEof(group_descriptions_file) do
		line := Gets(group_descriptions_file);
		if IsEof(line) then
			break;
		end if;
		parts := Split(line, "|");
		assert #parts eq 2;
		group_label := parts[1];
		group_desc := parts[2];
		G := MakeBigGroup(group_desc, group_label);
		// The trivial group has not been encountered in divisions.txt.
		if not IsDefined(ccs, group_label) then
			ccs[group_label] := [];
		end if;
		cc_gens := [LoadElt(cc[2], G) : cc in ccs[group_label]];
		G := G`MagmaGrp;
		
		ex, dat := MaybeGetGroupData(cache, G);
		if ex then
			imbs := [[imb`bound[InertiaTypeGeneratedBy(dat`coords, g)] : g in cc_gens] : imb in dat`imbs];
			imbs_string := ArrayString([
				ArrayString([Sprintf("\"%o\"", val) : val in imb]) : imb in imbs
			]);
			Write("imbs.out", Sprintf("%o|%o", group_label, imbs_string));
		else
			nr_groups_not_computed +:= 1;
		end if;
	end while;
	print "Number of groups not computed:", nr_groups_not_computed;
	delete group_descriptions_file;
end procedure;
